name: apps_kurir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6
  dropdown_search: ^5.0.5
  http: ^0.13.5
  d_method: ^0.2.0
  d_view: ^0.0.3
  flutter_barcode_scanner: ^2.0.0
  audioplayers: ^4.1.0
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.2.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.2
  flutter_spinkit: ^5.2.0
  d_info: ^0.2.2
  cool_alert: ^2.0.1
  intl: ^0.18.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/default.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter: 
  assets: 
    - assets/img/
    - assets/notifacation.mp3
    - assets/Salah.mp3
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Light.ttf
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
  uses-material-design: true

